# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Michelle Miller
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Michelle Miller.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Content
content:
  ## Social media links
  social:
    blog: http://blog.michellemiller.io/
    github: https://github.com/chellimiller/
    linkedin: https://www.linkedin.com/in/chellicmiller/
    stackoverflow: https://stackoverflow.com/users/6832300/michelle-miller
    codesignal: https://app.codesignal.com/profile/chelli_m
    instructables: https://www.instructables.com/member/chellicmiller/
    freelancer: https://www.freelancer.com/u/ChelliMiller
  credits:
    photos:
      label: "Photography: Noah J Miller"
      url: https://www.linkedin.com/in/noah-miller-482404142/
    cssreset:
      label: "CSS Reset: Normalize CSS"
      url: https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css
    icons:
      label: "Icons: Feather Icons"
      url: https://feathericons.com/
    fonts:
      label: "Font: Roboto"
      url: https://fonts.google.com/specimen/Roboto

  about:
    image:
      url: /assets/img/self-profile.png
      alt: It's me!
    title: Hello, I'm Michelle
    content: >-
      I'm a software engineer living in Tempe, Arizona.
      I specialize in TypeScript, React, automated testing, accessibility, and fullstack software development.
      I'm deeply committed to continuous learning and writing high-quality software.

# Build settings
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
